import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import { createAdminClient } from "@/lib/supabase/admin";
import { londonDateKey, londonDayRange } from "@/lib/utils";

/**
 * End-of-day summaries. Two kinds, written from real rows only:
 *
 *  - "operations": what happened on each job today, assembled from the notes
 *    the crew logged on site plus their timesheet hours, plus a look at
 *    what's on tomorrow and anything that needs chasing. Everyone reads this.
 *  - "financial": the money digest. Office/admin only.
 *
 * Both are generated by the same engine so the cron route and the on-demand
 * "generate now" button can't drift apart.
 */

export type SummaryKind = "operations" | "financial";

function dayRangeISO(dateKey: string) {
  const { start, end } = londonDayRange(dateKey);
  return { start: start.toISOString(), end: end.toISOString() };
}

function nextDayKey(dateKey: string): string {
  const [y, m, d] = dateKey.split("-").map(Number);
  return londonDateKey(new Date(Date.UTC(y, m - 1, d + 1, 12)));
}

function hoursFromMinutes(minutes: number): number {
  return Math.round((minutes / 60) * 10) / 10;
}

// ---------------------------------------------------------------------------
// Operations snapshot — grouped by job
// ---------------------------------------------------------------------------

export interface JobActivity {
  job_number: string;
  job_name: string;
  status: string;
  site: string | null;
  hours: number;
  people: string[];
  notes: { author: string; body: string }[];
  tasks_completed: string[];
  appointment_status: string | null;
}

export interface OperationsSnapshot {
  date: string;
  jobs: JobActivity[];
  total_hours: number;
  people_on_site: number;
  tomorrow: { job: string; site: string | null; time: string; crew: string[] }[];
  attention: string[];
}

export async function buildOperationsSnapshot(dateKey: string): Promise<OperationsSnapshot> {
  const supabase = createAdminClient();
  const { start, end } = dayRangeISO(dateKey);
  const tomorrowKey = nextDayKey(dateKey);
  const { start: tStart, end: tEnd } = dayRangeISO(tomorrowKey);

  const [notesRes, timesheetsRes, tasksRes, apptsRes, tomorrowRes, openTasksRes, unapprovedRes] =
    await Promise.all([
      supabase
        .from("job_notes")
        .select("body, created_at, job:jobs(job_number, job_name, status, site:sites(label, address_line1)), author:profiles(full_name)")
        .gte("created_at", start)
        .lt("created_at", end)
        .order("created_at", { ascending: true }),
      supabase
        .from("timesheets")
        .select("duration_minutes, job:jobs(job_number, job_name, status, site:sites(label, address_line1)), profile:profiles(full_name)")
        .gte("started_at", start)
        .lt("started_at", end)
        .not("duration_minutes", "is", null),
      supabase
        .from("job_tasks")
        .select("title, job:jobs(job_number, job_name, status, site:sites(label, address_line1))")
        .eq("status", "completed")
        .gte("updated_at", start)
        .lt("updated_at", end),
      supabase
        .from("appointments")
        .select("status, job:jobs(job_number)")
        .gte("starts_at", start)
        .lt("starts_at", end),
      supabase
        .from("appointments")
        .select("starts_at, job:jobs(job_number, job_name), site:sites(label, address_line1), assignments:appointment_assignments(profile:profiles(full_name), subcontractor:subcontractors(name))")
        .gte("starts_at", tStart)
        .lt("starts_at", tEnd)
        .order("starts_at", { ascending: true }),
      supabase
        .from("job_tasks")
        .select("title, due_date, job:jobs(job_number)")
        .neq("status", "completed")
        .not("due_date", "is", null)
        .lt("due_date", dateKey),
      supabase
        .from("timesheets")
        .select("id", { count: "exact", head: true })
        .eq("is_approved", false)
        .not("ended_at", "is", null),
    ]);

  type JobRef = { job_number: string; job_name: string; status: string; site: { label: string; address_line1: string } | null } | null;
  const byJob = new Map<string, JobActivity>();

  const ensure = (job: JobRef): JobActivity | null => {
    if (!job) return null;
    let entry = byJob.get(job.job_number);
    if (!entry) {
      entry = {
        job_number: job.job_number,
        job_name: job.job_name,
        status: job.status,
        site: job.site ? (job.site.label || job.site.address_line1) : null,
        hours: 0,
        people: [],
        notes: [],
        tasks_completed: [],
        appointment_status: null,
      };
      byJob.set(job.job_number, entry);
    }
    return entry;
  };

  for (const row of (notesRes.data ?? []) as unknown as { body: string; job: JobRef; author: { full_name: string } | null }[]) {
    const entry = ensure(row.job);
    if (entry) entry.notes.push({ author: row.author?.full_name ?? "Someone", body: row.body });
  }

  let totalMinutes = 0;
  const peopleOnSite = new Set<string>();
  // Accumulate in MINUTES and convert once at the end — rounding to 0.1h on
  // every row and then adding those rounded values drifts, and converting a
  // running hours figure back through the minutes helper is simply wrong.
  const minutesByJob = new Map<string, number>();

  for (const row of (timesheetsRes.data ?? []) as unknown as { duration_minutes: number; job: JobRef; profile: { full_name: string } | null }[]) {
    const entry = ensure(row.job);
    const minutes = Number(row.duration_minutes ?? 0);
    totalMinutes += minutes;
    const name = row.profile?.full_name ?? "Unknown";
    peopleOnSite.add(name);
    if (entry) {
      minutesByJob.set(entry.job_number, (minutesByJob.get(entry.job_number) ?? 0) + minutes);
      if (!entry.people.includes(name)) entry.people.push(name);
    }
  }

  for (const [jobNumber, minutes] of minutesByJob) {
    const entry = byJob.get(jobNumber);
    if (entry) entry.hours = hoursFromMinutes(minutes);
  }

  for (const row of (tasksRes.data ?? []) as unknown as { title: string; job: JobRef }[]) {
    const entry = ensure(row.job);
    if (entry) entry.tasks_completed.push(row.title);
  }

  for (const row of (apptsRes.data ?? []) as unknown as { status: string; job: { job_number: string } | null }[]) {
    if (!row.job) continue;
    const entry = byJob.get(row.job.job_number);
    if (entry) entry.appointment_status = row.status;
  }

  const tomorrow = ((tomorrowRes.data ?? []) as unknown as {
    starts_at: string;
    job: { job_number: string; job_name: string } | null;
    site: { label: string; address_line1: string } | null;
    assignments: { profile: { full_name: string } | null; subcontractor: { name: string } | null }[];
  }[]).map((a) => ({
    job: a.job ? `${a.job.job_number} — ${a.job.job_name}` : "Unassigned",
    site: a.site ? (a.site.label || a.site.address_line1) : null,
    time: new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/London" }).format(new Date(a.starts_at)),
    crew: (a.assignments ?? []).map((x) => x.profile?.full_name ?? x.subcontractor?.name ?? "").filter(Boolean),
  }));

  // Things worth flagging at 5pm rather than discovering next week.
  const attention: string[] = [];
  const overdueTasks = (openTasksRes.data ?? []) as unknown as { title: string; job: { job_number: string } | null }[];
  if (overdueTasks.length > 0) {
    attention.push(
      `${overdueTasks.length} task${overdueTasks.length === 1 ? "" : "s"} past their due date: ${overdueTasks
        .slice(0, 4)
        .map((t) => `${t.job?.job_number ?? "?"} — ${t.title}`)
        .join("; ")}${overdueTasks.length > 4 ? "…" : ""}`
    );
  }
  const unapproved = unapprovedRes.count ?? 0;
  if (unapproved > 0) {
    attention.push(`${unapproved} finished timesheet${unapproved === 1 ? "" : "s"} still waiting for approval.`);
  }
  const workedNoNotes = [...byJob.values()].filter((j) => j.hours > 0 && j.notes.length === 0);
  if (workedNoNotes.length > 0) {
    attention.push(
      `Hours logged but no site notes written on: ${workedNoNotes.map((j) => j.job_number).join(", ")}.`
    );
  }

  return {
    date: dateKey,
    jobs: [...byJob.values()].sort((a, b) => b.hours - a.hours),
    total_hours: hoursFromMinutes(totalMinutes),
    people_on_site: peopleOnSite.size,
    tomorrow,
    attention,
  };
}

// ---------------------------------------------------------------------------
// Financial snapshot
// ---------------------------------------------------------------------------

export interface FinancialSnapshot {
  date: string;
  quotes_sent_count: number;
  quotes_sent_value: number;
  quotes_accepted_count: number;
  quotes_accepted_value: number;
  invoices_sent_count: number;
  invoices_sent_value: number;
  payments_received_value: number;
  costs_logged_value: number;
  new_enquiries: number;
  jobs_completed: string[];
  overdue_invoices_count: number;
  overdue_invoices_total: number;
}

export async function buildFinancialSnapshot(dateKey: string): Promise<FinancialSnapshot> {
  const supabase = createAdminClient();
  const { start, end } = dayRangeISO(dateKey);

  const [quotesSent, quotesAccepted, invoicesSent, payments, costs, enquiries, completed, overdue] =
    await Promise.all([
      supabase.from("quotes").select("grand_total", { count: "exact" }).gte("sent_at", start).lt("sent_at", end),
      supabase.from("quotes").select("grand_total", { count: "exact" }).gte("accepted_at", start).lt("accepted_at", end),
      supabase.from("invoices").select("total", { count: "exact" }).gte("sent_at", start).lt("sent_at", end),
      supabase.from("payments").select("amount").eq("paid_date", dateKey),
      supabase.from("job_costs").select("total").eq("incurred_date", dateKey),
      supabase.from("enquiries").select("id", { count: "exact", head: true }).eq("date_received", dateKey),
      supabase.from("jobs").select("job_number, job_name").eq("actual_completion_date", dateKey),
      supabase.from("invoices").select("total, amount_paid").eq("status", "overdue"),
    ]);

  const sum = (rows: Record<string, unknown>[] | null, key: string) =>
    (rows ?? []).reduce((acc, r) => acc + Number(r[key] ?? 0), 0);

  return {
    date: dateKey,
    quotes_sent_count: quotesSent.count ?? 0,
    quotes_sent_value: sum(quotesSent.data, "grand_total"),
    quotes_accepted_count: quotesAccepted.count ?? 0,
    quotes_accepted_value: sum(quotesAccepted.data, "grand_total"),
    invoices_sent_count: invoicesSent.count ?? 0,
    invoices_sent_value: sum(invoicesSent.data, "total"),
    payments_received_value: sum(payments.data, "amount"),
    costs_logged_value: sum(costs.data, "total"),
    new_enquiries: enquiries.count ?? 0,
    jobs_completed: (completed.data ?? []).map((j) => `${j.job_number} — ${j.job_name}`),
    overdue_invoices_count: (overdue.data ?? []).length,
    overdue_invoices_total:
      (overdue.data ?? []).reduce((acc, i) => acc + (Number(i.total) - Number(i.amount_paid)), 0),
  };
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

const OPERATIONS_SYSTEM = `You write the end-of-day rundown for a UK trades/building company (W Smithers and Sons). It is read by everyone — office staff and the crew on the tools — so that everybody knows where every job stands.

You are given, for one day: each job worked on, the hours logged against it, who was on it, the notes the crew wrote on site, and any tasks they ticked off. Plus what's booked for tomorrow and anything needing attention.

Write it like a good foreman would at the end of the day:
- Open with one short line on the shape of the day (how many jobs, total hours, how many on site).
- Then a short paragraph per job, in the order given. Lead with the job number, then what actually happened — take it from the crew's notes, don't just restate the hours. Mention who was on it. If a note flags a problem, a delay, or something needed, say so plainly; that's the most useful thing on the page.
- If anything is booked for tomorrow, finish with a brief "Tomorrow" line covering what's on and who's where.
- If there are attention items, end with them as a short "Needs chasing" line.

Rules: plain UK English, no headings, no markdown, no bullet points — flowing prose with paragraph breaks. Never invent activity: if a job has hours but no notes, say the hours were logged but nothing was written up. Do not mention money, prices, invoices or margins at all. Keep the whole thing under 350 words.`;

const FINANCIAL_SYSTEM = `You write a short end-of-day money recap for the office manager of a UK trades/building company (W Smithers and Sons). You are given exact figures for one day, pulled from their job management system.

Write 3-5 sentences of plain, friendly UK English prose — no headings, no bullet points, no markdown. Only mention things that actually happened: a metric of 0 means it did not happen, so leave it out rather than writing "no invoices were sent". Money is GBP, formatted as £1,234.56. Finish with anything needing attention, such as overdue invoices. If almost everything is zero, it's fine to say it was a quiet day on the money side.`;

async function callClaude(system: string, payload: unknown, maxTokens: number): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      "ANTHROPIC_API_KEY is not set on this deployment — add it in Vercel and redeploy."
    );
  }
  const anthropic = new Anthropic({ apiKey });
  const model = process.env.ANTHROPIC_SUMMARY_MODEL || "claude-sonnet-4-5-20250929";

  const message = await anthropic.messages.create({
    model,
    max_tokens: maxTokens,
    system,
    messages: [{ role: "user", content: JSON.stringify(payload, null, 2) }],
  });

  const block = message.content.find((b) => b.type === "text");
  return block && "text" in block ? block.text.trim() : "";
}

export interface SummaryResult {
  kind: SummaryKind;
  saved: boolean;
  skipped?: string;
  error?: string;
}

/** Build, generate and store both summaries for a London calendar day. */
export async function generateDailySummaries(dateKey = londonDateKey()): Promise<SummaryResult[]> {
  const supabase = createAdminClient();
  const results: SummaryResult[] = [];

  // --- Operations -----------------------------------------------------
  try {
    const ops = await buildOperationsSnapshot(dateKey);
    if (ops.jobs.length === 0 && ops.tomorrow.length === 0) {
      results.push({ kind: "operations", saved: false, skipped: "Nothing happened on any job today." });
    } else {
      const content = await callClaude(OPERATIONS_SYSTEM, ops, 900);
      const { error } = await supabase.from("daily_summaries").upsert(
        { summary_date: dateKey, kind: "operations", content, stats: { ...ops } as unknown as Record<string, unknown>, generated_at: new Date().toISOString() },
        { onConflict: "summary_date,kind" }
      );
      results.push({ kind: "operations", saved: !error, error: error ? "Could not save the summary." : undefined });
    }
  } catch (err) {
    results.push({ kind: "operations", saved: false, error: err instanceof Error ? err.message : "Failed." });
  }

  // --- Financial ------------------------------------------------------
  try {
    const fin = await buildFinancialSnapshot(dateKey);
    const content = await callClaude(FINANCIAL_SYSTEM, fin, 500);
    const { error } = await supabase.from("daily_summaries").upsert(
      { summary_date: dateKey, kind: "financial", content, stats: { ...fin } as unknown as Record<string, unknown>, generated_at: new Date().toISOString() },
      { onConflict: "summary_date,kind" }
    );
    results.push({ kind: "financial", saved: !error, error: error ? "Could not save the summary." : undefined });
  } catch (err) {
    results.push({ kind: "financial", saved: false, error: err instanceof Error ? err.message : "Failed." });
  }

  // Notify everyone the operational rundown is up — that's the one the crew
  // are waiting on. Office also get it, and they can see the money one too.
  if (results.some((r) => r.kind === "operations" && r.saved)) {
    const { data: staff } = await supabase.from("profiles").select("id").eq("is_active", true);
    if (staff && staff.length > 0) {
      await supabase.from("notifications").insert(
        staff.map((p) => ({
          profile_id: p.id,
          title: "Today's job rundown is ready",
          body: "A summary of what happened on every job today.",
          link_path: "/dashboard",
        }))
      );
    }
  }

  return results;
}
